global using AntiIdle.Common.Flash;
global using static AntiIdle.Common.Flash.DeadStubs;
global using static AntiIdle.Common.Flash.Extension;
global using static AntiIdle.Common.Flash.FlashRandom;
global using static AntiIdle.Common.Flash.Numbers;
global using static AntiIdle.Common.Flash.Version;
global using static AntiIdle.Common.Global;
global using static AntiIdle.Common.Globals.ColorHelper;
global using AntiIdle.Common.Nodes;
global using static AntiIdle.Common.Nodes.NodeExtensions;
global using AntiIdle.Extensions;
